{% set name = "sphractal" %}
{% set version = "0.28.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sphractal-{{ version }}.tar.gz
  sha256: 808e880be50584a11ad8a1efef9efb275125e9cc3b67f8085d0befe27a5f5f7b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.9
    - matplotlib-base >=3.7.1
    - statsmodels >=0.14.0
    - scipy >=1.11.1
    - numba >=0.57.1
    - numpy >=1.22,<1.25

test:
  imports:
    - sphractal
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Jon-Ting/sphractal
  summary: Package to estimate fractal dimension of 3D surfaces formed from overlapping spheres via box-counting algorithm.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    Sphractal is a package that provides functionality to estimate the fractal dimension of complex 3D surfaces formed from overlapping spheres via box-counting algorithm. 
  doc_url: https://sphractal.readthedocs.io/
  dev_url: https://github.com/Jon-Ting/sphractal

extra:
  recipe-maintainers:
    - Jon-Ting
